# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v3/diff/Universal/Transaction.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='v3/diff/Universal/Transaction.proto',
  package='v3.diff.universal',
  syntax='proto3',
  serialized_pb=_b('\n#v3/diff/Universal/Transaction.proto\x12\x11v3.diff.universal\"\xeb\x02\n\x0bTransaction\x12\x0c\n\x04path\x18\x01 \x03(\x05\x12\x15\n\x0b\x64\x61ta_double\x18\x02 \x01(\x01H\x00\x12\x14\n\ndata_float\x18\x03 \x01(\x02H\x00\x12\x14\n\ndata_int32\x18\x04 \x01(\x05H\x00\x12\x14\n\ndata_int64\x18\x05 \x01(\x03H\x00\x12\x15\n\x0b\x64\x61ta_uint32\x18\x06 \x01(\rH\x00\x12\x15\n\x0b\x64\x61ta_uint64\x18\x07 \x01(\x04H\x00\x12\x13\n\tdata_bool\x18\x08 \x01(\x08H\x00\x12\x15\n\x0b\x64\x61ta_string\x18\t \x01(\tH\x00\x12\x14\n\ndata_bytes\x18\n \x01(\x0cH\x00\x12\x38\n\toperation\x18\x0b \x01(\x0e\x32%.v3.diff.universal.Transaction.OpType\x12\x13\n\x0b\x64\x61ta_or_key\x18\x0c \x01(\x0c\x12\r\n\x05value\x18\r \x01(\x0c\"\x1d\n\x06OpType\x12\x07\n\x03\x41\x44\x44\x10\x00\x12\n\n\x06\x44\x45LETE\x10\x01\x42\x08\n\x06scalarb\x06proto3')
)



_TRANSACTION_OPTYPE = _descriptor.EnumDescriptor(
  name='OpType',
  full_name='v3.diff.universal.Transaction.OpType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ADD', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DELETE', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=383,
  serialized_end=412,
)
_sym_db.RegisterEnumDescriptor(_TRANSACTION_OPTYPE)


_TRANSACTION = _descriptor.Descriptor(
  name='Transaction',
  full_name='v3.diff.universal.Transaction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='v3.diff.universal.Transaction.path', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_double', full_name='v3.diff.universal.Transaction.data_double', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_float', full_name='v3.diff.universal.Transaction.data_float', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_int32', full_name='v3.diff.universal.Transaction.data_int32', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_int64', full_name='v3.diff.universal.Transaction.data_int64', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_uint32', full_name='v3.diff.universal.Transaction.data_uint32', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_uint64', full_name='v3.diff.universal.Transaction.data_uint64', index=6,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_bool', full_name='v3.diff.universal.Transaction.data_bool', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_string', full_name='v3.diff.universal.Transaction.data_string', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_bytes', full_name='v3.diff.universal.Transaction.data_bytes', index=9,
      number=10, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='operation', full_name='v3.diff.universal.Transaction.operation', index=10,
      number=11, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_or_key', full_name='v3.diff.universal.Transaction.data_or_key', index=11,
      number=12, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='v3.diff.universal.Transaction.value', index=12,
      number=13, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TRANSACTION_OPTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='scalar', full_name='v3.diff.universal.Transaction.scalar',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=59,
  serialized_end=422,
)

_TRANSACTION.fields_by_name['operation'].enum_type = _TRANSACTION_OPTYPE
_TRANSACTION_OPTYPE.containing_type = _TRANSACTION
_TRANSACTION.oneofs_by_name['scalar'].fields.append(
  _TRANSACTION.fields_by_name['data_double'])
_TRANSACTION.fields_by_name['data_double'].containing_oneof = _TRANSACTION.oneofs_by_name['scalar']
_TRANSACTION.oneofs_by_name['scalar'].fields.append(
  _TRANSACTION.fields_by_name['data_float'])
_TRANSACTION.fields_by_name['data_float'].containing_oneof = _TRANSACTION.oneofs_by_name['scalar']
_TRANSACTION.oneofs_by_name['scalar'].fields.append(
  _TRANSACTION.fields_by_name['data_int32'])
_TRANSACTION.fields_by_name['data_int32'].containing_oneof = _TRANSACTION.oneofs_by_name['scalar']
_TRANSACTION.oneofs_by_name['scalar'].fields.append(
  _TRANSACTION.fields_by_name['data_int64'])
_TRANSACTION.fields_by_name['data_int64'].containing_oneof = _TRANSACTION.oneofs_by_name['scalar']
_TRANSACTION.oneofs_by_name['scalar'].fields.append(
  _TRANSACTION.fields_by_name['data_uint32'])
_TRANSACTION.fields_by_name['data_uint32'].containing_oneof = _TRANSACTION.oneofs_by_name['scalar']
_TRANSACTION.oneofs_by_name['scalar'].fields.append(
  _TRANSACTION.fields_by_name['data_uint64'])
_TRANSACTION.fields_by_name['data_uint64'].containing_oneof = _TRANSACTION.oneofs_by_name['scalar']
_TRANSACTION.oneofs_by_name['scalar'].fields.append(
  _TRANSACTION.fields_by_name['data_bool'])
_TRANSACTION.fields_by_name['data_bool'].containing_oneof = _TRANSACTION.oneofs_by_name['scalar']
_TRANSACTION.oneofs_by_name['scalar'].fields.append(
  _TRANSACTION.fields_by_name['data_string'])
_TRANSACTION.fields_by_name['data_string'].containing_oneof = _TRANSACTION.oneofs_by_name['scalar']
_TRANSACTION.oneofs_by_name['scalar'].fields.append(
  _TRANSACTION.fields_by_name['data_bytes'])
_TRANSACTION.fields_by_name['data_bytes'].containing_oneof = _TRANSACTION.oneofs_by_name['scalar']
DESCRIPTOR.message_types_by_name['Transaction'] = _TRANSACTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Transaction = _reflection.GeneratedProtocolMessageType('Transaction', (_message.Message,), dict(
  DESCRIPTOR = _TRANSACTION,
  __module__ = 'v3.diff.Universal.Transaction_pb2'
  # @@protoc_insertion_point(class_scope:v3.diff.universal.Transaction)
  ))
_sym_db.RegisterMessage(Transaction)


# @@protoc_insertion_point(module_scope)
