// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v3/diff/Intrusive/TestMessageIntrusive.proto

#include "v3/diff/Intrusive/TestMessageIntrusive.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace v3 {
namespace diff {
namespace intrusive {
class TestMessageIntrusive_TestSection1DefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<TestMessageIntrusive_TestSection1>
      _instance;
} _TestMessageIntrusive_TestSection1_default_instance_;
class TestMessageIntrusive_TestSection2DefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<TestMessageIntrusive_TestSection2>
      _instance;
} _TestMessageIntrusive_TestSection2_default_instance_;
class TestMessageIntrusive_MapValuesEntry_DoNotUseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<TestMessageIntrusive_MapValuesEntry_DoNotUse>
      _instance;
} _TestMessageIntrusive_MapValuesEntry_DoNotUse_default_instance_;
class TestMessageIntrusiveDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<TestMessageIntrusive>
      _instance;
} _TestMessageIntrusive_default_instance_;
}  // namespace intrusive
}  // namespace diff
}  // namespace v3
namespace protobuf_v3_2fdiff_2fIntrusive_2fTestMessageIntrusive_2eproto {
void InitDefaultsTestMessageIntrusive_TestSection1Impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::v3::diff::intrusive::_TestMessageIntrusive_TestSection1_default_instance_;
    new (ptr) ::v3::diff::intrusive::TestMessageIntrusive_TestSection1();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::v3::diff::intrusive::TestMessageIntrusive_TestSection1::InitAsDefaultInstance();
}

void InitDefaultsTestMessageIntrusive_TestSection1() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsTestMessageIntrusive_TestSection1Impl);
}

void InitDefaultsTestMessageIntrusive_TestSection2Impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::v3::diff::intrusive::_TestMessageIntrusive_TestSection2_default_instance_;
    new (ptr) ::v3::diff::intrusive::TestMessageIntrusive_TestSection2();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::v3::diff::intrusive::TestMessageIntrusive_TestSection2::InitAsDefaultInstance();
}

void InitDefaultsTestMessageIntrusive_TestSection2() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsTestMessageIntrusive_TestSection2Impl);
}

void InitDefaultsTestMessageIntrusive_MapValuesEntry_DoNotUseImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_v3_2fdiff_2fIntrusive_2fTestMessageIntrusive_2eproto::InitDefaultsTestMessageIntrusive_TestSection2();
  {
    void* ptr = &::v3::diff::intrusive::_TestMessageIntrusive_MapValuesEntry_DoNotUse_default_instance_;
    new (ptr) ::v3::diff::intrusive::TestMessageIntrusive_MapValuesEntry_DoNotUse();
  }
  ::v3::diff::intrusive::TestMessageIntrusive_MapValuesEntry_DoNotUse::InitAsDefaultInstance();
}

void InitDefaultsTestMessageIntrusive_MapValuesEntry_DoNotUse() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsTestMessageIntrusive_MapValuesEntry_DoNotUseImpl);
}

void InitDefaultsTestMessageIntrusiveImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_v3_2fdiff_2fIntrusive_2fTestMessageIntrusive_2eproto::InitDefaultsTestMessageIntrusive_TestSection1();
  protobuf_v3_2fdiff_2fIntrusive_2fTestMessageIntrusive_2eproto::InitDefaultsTestMessageIntrusive_TestSection2();
  protobuf_v3_2fdiff_2fIntrusive_2fTestMessageIntrusive_2eproto::InitDefaultsTestMessageIntrusive_MapValuesEntry_DoNotUse();
  {
    void* ptr = &::v3::diff::intrusive::_TestMessageIntrusive_default_instance_;
    new (ptr) ::v3::diff::intrusive::TestMessageIntrusive();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::v3::diff::intrusive::TestMessageIntrusive::InitAsDefaultInstance();
}

void InitDefaultsTestMessageIntrusive() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsTestMessageIntrusiveImpl);
}

::google::protobuf::Metadata file_level_metadata[4];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::v3::diff::intrusive::TestMessageIntrusive_TestSection1, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::v3::diff::intrusive::TestMessageIntrusive_TestSection1, diff_type_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::v3::diff::intrusive::TestMessageIntrusive_TestSection1, value1_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::v3::diff::intrusive::TestMessageIntrusive_TestSection1, value2_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::v3::diff::intrusive::TestMessageIntrusive_TestSection2, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::v3::diff::intrusive::TestMessageIntrusive_TestSection2, diff_type_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::v3::diff::intrusive::TestMessageIntrusive_TestSection2, diff_order_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::v3::diff::intrusive::TestMessageIntrusive_TestSection2, value3_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::v3::diff::intrusive::TestMessageIntrusive_TestSection2, value4_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::v3::diff::intrusive::TestMessageIntrusive_MapValuesEntry_DoNotUse, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::v3::diff::intrusive::TestMessageIntrusive_MapValuesEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::v3::diff::intrusive::TestMessageIntrusive_MapValuesEntry_DoNotUse, key_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::v3::diff::intrusive::TestMessageIntrusive_MapValuesEntry_DoNotUse, value_),
  0,
  1,
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::v3::diff::intrusive::TestMessageIntrusive, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::v3::diff::intrusive::TestMessageIntrusive, type_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::v3::diff::intrusive::TestMessageIntrusive, section1_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::v3::diff::intrusive::TestMessageIntrusive, section2_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::v3::diff::intrusive::TestMessageIntrusive, value5_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::v3::diff::intrusive::TestMessageIntrusive, value6_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::v3::diff::intrusive::TestMessageIntrusive, array_values_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::v3::diff::intrusive::TestMessageIntrusive, map_values_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::v3::diff::intrusive::TestMessageIntrusive_TestSection1)},
  { 8, -1, sizeof(::v3::diff::intrusive::TestMessageIntrusive_TestSection2)},
  { 17, 24, sizeof(::v3::diff::intrusive::TestMessageIntrusive_MapValuesEntry_DoNotUse)},
  { 26, -1, sizeof(::v3::diff::intrusive::TestMessageIntrusive)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::v3::diff::intrusive::_TestMessageIntrusive_TestSection1_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::v3::diff::intrusive::_TestMessageIntrusive_TestSection2_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::v3::diff::intrusive::_TestMessageIntrusive_MapValuesEntry_DoNotUse_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::v3::diff::intrusive::_TestMessageIntrusive_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "v3/diff/Intrusive/TestMessageIntrusive.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 4);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n,v3/diff/Intrusive/TestMessageIntrusive"
      ".proto\022\021v3.diff.intrusive\032%v3/diff/Intru"
      "sive/IntrusiveDiff.proto\"\322\005\n\024TestMessage"
      "Intrusive\022,\n\004type\030\001 \001(\0162\036.v3.diff.intrus"
      "ive.MessageType\022F\n\010section1\030\002 \001(\01324.v3.d"
      "iff.intrusive.TestMessageIntrusive.TestS"
      "ection1\022F\n\010section2\030\003 \001(\01324.v3.diff.intr"
      "usive.TestMessageIntrusive.TestSection2\022"
      "\016\n\006value5\030\004 \001(\r\022\016\n\006value6\030\005 \001(\001\022J\n\014array"
      "_values\030\006 \003(\01324.v3.diff.intrusive.TestMe"
      "ssageIntrusive.TestSection1\022J\n\nmap_value"
      "s\030\007 \003(\01326.v3.diff.intrusive.TestMessageI"
      "ntrusive.MapValuesEntry\032c\n\014TestSection1\022"
      "3\n\tdiff_type\030\001 \001(\0162 .v3.diff.intrusive.O"
      "perationType\022\016\n\006value1\030\002 \001(\r\022\016\n\006value2\030\003"
      " \001(\r\032w\n\014TestSection2\0223\n\tdiff_type\030\001 \001(\0162"
      " .v3.diff.intrusive.OperationType\022\022\n\ndif"
      "f_order\030\002 \001(\005\022\016\n\006value3\030\003 \001(\001\022\016\n\006value4\030"
      "\004 \001(\001\032f\n\016MapValuesEntry\022\013\n\003key\030\001 \001(\005\022C\n\005"
      "value\030\002 \001(\01324.v3.diff.intrusive.TestMess"
      "ageIntrusive.TestSection2:\0028\001b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 837);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "v3/diff/Intrusive/TestMessageIntrusive.proto", &protobuf_RegisterTypes);
  ::protobuf_v3_2fdiff_2fIntrusive_2fIntrusiveDiff_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_v3_2fdiff_2fIntrusive_2fTestMessageIntrusive_2eproto
namespace v3 {
namespace diff {
namespace intrusive {

// ===================================================================

void TestMessageIntrusive_TestSection1::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int TestMessageIntrusive_TestSection1::kDiffTypeFieldNumber;
const int TestMessageIntrusive_TestSection1::kValue1FieldNumber;
const int TestMessageIntrusive_TestSection1::kValue2FieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

TestMessageIntrusive_TestSection1::TestMessageIntrusive_TestSection1()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_v3_2fdiff_2fIntrusive_2fTestMessageIntrusive_2eproto::InitDefaultsTestMessageIntrusive_TestSection1();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:v3.diff.intrusive.TestMessageIntrusive.TestSection1)
}
TestMessageIntrusive_TestSection1::TestMessageIntrusive_TestSection1(const TestMessageIntrusive_TestSection1& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&diff_type_, &from.diff_type_,
    static_cast<size_t>(reinterpret_cast<char*>(&value2_) -
    reinterpret_cast<char*>(&diff_type_)) + sizeof(value2_));
  // @@protoc_insertion_point(copy_constructor:v3.diff.intrusive.TestMessageIntrusive.TestSection1)
}

void TestMessageIntrusive_TestSection1::SharedCtor() {
  ::memset(&diff_type_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&value2_) -
      reinterpret_cast<char*>(&diff_type_)) + sizeof(value2_));
  _cached_size_ = 0;
}

TestMessageIntrusive_TestSection1::~TestMessageIntrusive_TestSection1() {
  // @@protoc_insertion_point(destructor:v3.diff.intrusive.TestMessageIntrusive.TestSection1)
  SharedDtor();
}

void TestMessageIntrusive_TestSection1::SharedDtor() {
}

void TestMessageIntrusive_TestSection1::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TestMessageIntrusive_TestSection1::descriptor() {
  ::protobuf_v3_2fdiff_2fIntrusive_2fTestMessageIntrusive_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_v3_2fdiff_2fIntrusive_2fTestMessageIntrusive_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const TestMessageIntrusive_TestSection1& TestMessageIntrusive_TestSection1::default_instance() {
  ::protobuf_v3_2fdiff_2fIntrusive_2fTestMessageIntrusive_2eproto::InitDefaultsTestMessageIntrusive_TestSection1();
  return *internal_default_instance();
}

TestMessageIntrusive_TestSection1* TestMessageIntrusive_TestSection1::New(::google::protobuf::Arena* arena) const {
  TestMessageIntrusive_TestSection1* n = new TestMessageIntrusive_TestSection1;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void TestMessageIntrusive_TestSection1::Clear() {
// @@protoc_insertion_point(message_clear_start:v3.diff.intrusive.TestMessageIntrusive.TestSection1)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&diff_type_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&value2_) -
      reinterpret_cast<char*>(&diff_type_)) + sizeof(value2_));
  _internal_metadata_.Clear();
}

bool TestMessageIntrusive_TestSection1::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:v3.diff.intrusive.TestMessageIntrusive.TestSection1)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .v3.diff.intrusive.OperationType diff_type = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_diff_type(static_cast< ::v3::diff::intrusive::OperationType >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 value1 = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &value1_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 value2 = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &value2_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:v3.diff.intrusive.TestMessageIntrusive.TestSection1)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:v3.diff.intrusive.TestMessageIntrusive.TestSection1)
  return false;
#undef DO_
}

void TestMessageIntrusive_TestSection1::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:v3.diff.intrusive.TestMessageIntrusive.TestSection1)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .v3.diff.intrusive.OperationType diff_type = 1;
  if (this->diff_type() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->diff_type(), output);
  }

  // uint32 value1 = 2;
  if (this->value1() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->value1(), output);
  }

  // uint32 value2 = 3;
  if (this->value2() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->value2(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:v3.diff.intrusive.TestMessageIntrusive.TestSection1)
}

::google::protobuf::uint8* TestMessageIntrusive_TestSection1::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:v3.diff.intrusive.TestMessageIntrusive.TestSection1)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .v3.diff.intrusive.OperationType diff_type = 1;
  if (this->diff_type() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->diff_type(), target);
  }

  // uint32 value1 = 2;
  if (this->value1() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->value1(), target);
  }

  // uint32 value2 = 3;
  if (this->value2() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->value2(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:v3.diff.intrusive.TestMessageIntrusive.TestSection1)
  return target;
}

size_t TestMessageIntrusive_TestSection1::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:v3.diff.intrusive.TestMessageIntrusive.TestSection1)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // .v3.diff.intrusive.OperationType diff_type = 1;
  if (this->diff_type() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->diff_type());
  }

  // uint32 value1 = 2;
  if (this->value1() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->value1());
  }

  // uint32 value2 = 3;
  if (this->value2() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->value2());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void TestMessageIntrusive_TestSection1::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:v3.diff.intrusive.TestMessageIntrusive.TestSection1)
  GOOGLE_DCHECK_NE(&from, this);
  const TestMessageIntrusive_TestSection1* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const TestMessageIntrusive_TestSection1>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:v3.diff.intrusive.TestMessageIntrusive.TestSection1)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:v3.diff.intrusive.TestMessageIntrusive.TestSection1)
    MergeFrom(*source);
  }
}

void TestMessageIntrusive_TestSection1::MergeFrom(const TestMessageIntrusive_TestSection1& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:v3.diff.intrusive.TestMessageIntrusive.TestSection1)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.diff_type() != 0) {
    set_diff_type(from.diff_type());
  }
  if (from.value1() != 0) {
    set_value1(from.value1());
  }
  if (from.value2() != 0) {
    set_value2(from.value2());
  }
}

void TestMessageIntrusive_TestSection1::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:v3.diff.intrusive.TestMessageIntrusive.TestSection1)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TestMessageIntrusive_TestSection1::CopyFrom(const TestMessageIntrusive_TestSection1& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:v3.diff.intrusive.TestMessageIntrusive.TestSection1)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TestMessageIntrusive_TestSection1::IsInitialized() const {
  return true;
}

void TestMessageIntrusive_TestSection1::Swap(TestMessageIntrusive_TestSection1* other) {
  if (other == this) return;
  InternalSwap(other);
}
void TestMessageIntrusive_TestSection1::InternalSwap(TestMessageIntrusive_TestSection1* other) {
  using std::swap;
  swap(diff_type_, other->diff_type_);
  swap(value1_, other->value1_);
  swap(value2_, other->value2_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata TestMessageIntrusive_TestSection1::GetMetadata() const {
  protobuf_v3_2fdiff_2fIntrusive_2fTestMessageIntrusive_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_v3_2fdiff_2fIntrusive_2fTestMessageIntrusive_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void TestMessageIntrusive_TestSection2::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int TestMessageIntrusive_TestSection2::kDiffTypeFieldNumber;
const int TestMessageIntrusive_TestSection2::kDiffOrderFieldNumber;
const int TestMessageIntrusive_TestSection2::kValue3FieldNumber;
const int TestMessageIntrusive_TestSection2::kValue4FieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

TestMessageIntrusive_TestSection2::TestMessageIntrusive_TestSection2()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_v3_2fdiff_2fIntrusive_2fTestMessageIntrusive_2eproto::InitDefaultsTestMessageIntrusive_TestSection2();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:v3.diff.intrusive.TestMessageIntrusive.TestSection2)
}
TestMessageIntrusive_TestSection2::TestMessageIntrusive_TestSection2(const TestMessageIntrusive_TestSection2& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&diff_type_, &from.diff_type_,
    static_cast<size_t>(reinterpret_cast<char*>(&value4_) -
    reinterpret_cast<char*>(&diff_type_)) + sizeof(value4_));
  // @@protoc_insertion_point(copy_constructor:v3.diff.intrusive.TestMessageIntrusive.TestSection2)
}

void TestMessageIntrusive_TestSection2::SharedCtor() {
  ::memset(&diff_type_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&value4_) -
      reinterpret_cast<char*>(&diff_type_)) + sizeof(value4_));
  _cached_size_ = 0;
}

TestMessageIntrusive_TestSection2::~TestMessageIntrusive_TestSection2() {
  // @@protoc_insertion_point(destructor:v3.diff.intrusive.TestMessageIntrusive.TestSection2)
  SharedDtor();
}

void TestMessageIntrusive_TestSection2::SharedDtor() {
}

void TestMessageIntrusive_TestSection2::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TestMessageIntrusive_TestSection2::descriptor() {
  ::protobuf_v3_2fdiff_2fIntrusive_2fTestMessageIntrusive_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_v3_2fdiff_2fIntrusive_2fTestMessageIntrusive_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const TestMessageIntrusive_TestSection2& TestMessageIntrusive_TestSection2::default_instance() {
  ::protobuf_v3_2fdiff_2fIntrusive_2fTestMessageIntrusive_2eproto::InitDefaultsTestMessageIntrusive_TestSection2();
  return *internal_default_instance();
}

TestMessageIntrusive_TestSection2* TestMessageIntrusive_TestSection2::New(::google::protobuf::Arena* arena) const {
  TestMessageIntrusive_TestSection2* n = new TestMessageIntrusive_TestSection2;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void TestMessageIntrusive_TestSection2::Clear() {
// @@protoc_insertion_point(message_clear_start:v3.diff.intrusive.TestMessageIntrusive.TestSection2)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&diff_type_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&value4_) -
      reinterpret_cast<char*>(&diff_type_)) + sizeof(value4_));
  _internal_metadata_.Clear();
}

bool TestMessageIntrusive_TestSection2::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:v3.diff.intrusive.TestMessageIntrusive.TestSection2)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .v3.diff.intrusive.OperationType diff_type = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_diff_type(static_cast< ::v3::diff::intrusive::OperationType >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 diff_order = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &diff_order_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double value3 = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(25u /* 25 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &value3_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double value4 = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(33u /* 33 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &value4_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:v3.diff.intrusive.TestMessageIntrusive.TestSection2)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:v3.diff.intrusive.TestMessageIntrusive.TestSection2)
  return false;
#undef DO_
}

void TestMessageIntrusive_TestSection2::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:v3.diff.intrusive.TestMessageIntrusive.TestSection2)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .v3.diff.intrusive.OperationType diff_type = 1;
  if (this->diff_type() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->diff_type(), output);
  }

  // int32 diff_order = 2;
  if (this->diff_order() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->diff_order(), output);
  }

  // double value3 = 3;
  if (this->value3() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(3, this->value3(), output);
  }

  // double value4 = 4;
  if (this->value4() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(4, this->value4(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:v3.diff.intrusive.TestMessageIntrusive.TestSection2)
}

::google::protobuf::uint8* TestMessageIntrusive_TestSection2::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:v3.diff.intrusive.TestMessageIntrusive.TestSection2)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .v3.diff.intrusive.OperationType diff_type = 1;
  if (this->diff_type() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->diff_type(), target);
  }

  // int32 diff_order = 2;
  if (this->diff_order() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->diff_order(), target);
  }

  // double value3 = 3;
  if (this->value3() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(3, this->value3(), target);
  }

  // double value4 = 4;
  if (this->value4() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(4, this->value4(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:v3.diff.intrusive.TestMessageIntrusive.TestSection2)
  return target;
}

size_t TestMessageIntrusive_TestSection2::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:v3.diff.intrusive.TestMessageIntrusive.TestSection2)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // .v3.diff.intrusive.OperationType diff_type = 1;
  if (this->diff_type() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->diff_type());
  }

  // int32 diff_order = 2;
  if (this->diff_order() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->diff_order());
  }

  // double value3 = 3;
  if (this->value3() != 0) {
    total_size += 1 + 8;
  }

  // double value4 = 4;
  if (this->value4() != 0) {
    total_size += 1 + 8;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void TestMessageIntrusive_TestSection2::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:v3.diff.intrusive.TestMessageIntrusive.TestSection2)
  GOOGLE_DCHECK_NE(&from, this);
  const TestMessageIntrusive_TestSection2* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const TestMessageIntrusive_TestSection2>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:v3.diff.intrusive.TestMessageIntrusive.TestSection2)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:v3.diff.intrusive.TestMessageIntrusive.TestSection2)
    MergeFrom(*source);
  }
}

void TestMessageIntrusive_TestSection2::MergeFrom(const TestMessageIntrusive_TestSection2& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:v3.diff.intrusive.TestMessageIntrusive.TestSection2)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.diff_type() != 0) {
    set_diff_type(from.diff_type());
  }
  if (from.diff_order() != 0) {
    set_diff_order(from.diff_order());
  }
  if (from.value3() != 0) {
    set_value3(from.value3());
  }
  if (from.value4() != 0) {
    set_value4(from.value4());
  }
}

void TestMessageIntrusive_TestSection2::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:v3.diff.intrusive.TestMessageIntrusive.TestSection2)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TestMessageIntrusive_TestSection2::CopyFrom(const TestMessageIntrusive_TestSection2& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:v3.diff.intrusive.TestMessageIntrusive.TestSection2)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TestMessageIntrusive_TestSection2::IsInitialized() const {
  return true;
}

void TestMessageIntrusive_TestSection2::Swap(TestMessageIntrusive_TestSection2* other) {
  if (other == this) return;
  InternalSwap(other);
}
void TestMessageIntrusive_TestSection2::InternalSwap(TestMessageIntrusive_TestSection2* other) {
  using std::swap;
  swap(diff_type_, other->diff_type_);
  swap(diff_order_, other->diff_order_);
  swap(value3_, other->value3_);
  swap(value4_, other->value4_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata TestMessageIntrusive_TestSection2::GetMetadata() const {
  protobuf_v3_2fdiff_2fIntrusive_2fTestMessageIntrusive_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_v3_2fdiff_2fIntrusive_2fTestMessageIntrusive_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

TestMessageIntrusive_MapValuesEntry_DoNotUse::TestMessageIntrusive_MapValuesEntry_DoNotUse() {}
TestMessageIntrusive_MapValuesEntry_DoNotUse::TestMessageIntrusive_MapValuesEntry_DoNotUse(::google::protobuf::Arena* arena) : SuperType(arena) {}
void TestMessageIntrusive_MapValuesEntry_DoNotUse::MergeFrom(const TestMessageIntrusive_MapValuesEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::google::protobuf::Metadata TestMessageIntrusive_MapValuesEntry_DoNotUse::GetMetadata() const {
  ::protobuf_v3_2fdiff_2fIntrusive_2fTestMessageIntrusive_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_v3_2fdiff_2fIntrusive_2fTestMessageIntrusive_2eproto::file_level_metadata[2];
}
void TestMessageIntrusive_MapValuesEntry_DoNotUse::MergeFrom(
    const ::google::protobuf::Message& other) {
  ::google::protobuf::Message::MergeFrom(other);
}


// ===================================================================

void TestMessageIntrusive::InitAsDefaultInstance() {
  ::v3::diff::intrusive::_TestMessageIntrusive_default_instance_._instance.get_mutable()->section1_ = const_cast< ::v3::diff::intrusive::TestMessageIntrusive_TestSection1*>(
      ::v3::diff::intrusive::TestMessageIntrusive_TestSection1::internal_default_instance());
  ::v3::diff::intrusive::_TestMessageIntrusive_default_instance_._instance.get_mutable()->section2_ = const_cast< ::v3::diff::intrusive::TestMessageIntrusive_TestSection2*>(
      ::v3::diff::intrusive::TestMessageIntrusive_TestSection2::internal_default_instance());
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int TestMessageIntrusive::kTypeFieldNumber;
const int TestMessageIntrusive::kSection1FieldNumber;
const int TestMessageIntrusive::kSection2FieldNumber;
const int TestMessageIntrusive::kValue5FieldNumber;
const int TestMessageIntrusive::kValue6FieldNumber;
const int TestMessageIntrusive::kArrayValuesFieldNumber;
const int TestMessageIntrusive::kMapValuesFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

TestMessageIntrusive::TestMessageIntrusive()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_v3_2fdiff_2fIntrusive_2fTestMessageIntrusive_2eproto::InitDefaultsTestMessageIntrusive();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:v3.diff.intrusive.TestMessageIntrusive)
}
TestMessageIntrusive::TestMessageIntrusive(const TestMessageIntrusive& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      array_values_(from.array_values_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  map_values_.MergeFrom(from.map_values_);
  if (from.has_section1()) {
    section1_ = new ::v3::diff::intrusive::TestMessageIntrusive_TestSection1(*from.section1_);
  } else {
    section1_ = NULL;
  }
  if (from.has_section2()) {
    section2_ = new ::v3::diff::intrusive::TestMessageIntrusive_TestSection2(*from.section2_);
  } else {
    section2_ = NULL;
  }
  ::memcpy(&type_, &from.type_,
    static_cast<size_t>(reinterpret_cast<char*>(&value6_) -
    reinterpret_cast<char*>(&type_)) + sizeof(value6_));
  // @@protoc_insertion_point(copy_constructor:v3.diff.intrusive.TestMessageIntrusive)
}

void TestMessageIntrusive::SharedCtor() {
  ::memset(&section1_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&value6_) -
      reinterpret_cast<char*>(&section1_)) + sizeof(value6_));
  _cached_size_ = 0;
}

TestMessageIntrusive::~TestMessageIntrusive() {
  // @@protoc_insertion_point(destructor:v3.diff.intrusive.TestMessageIntrusive)
  SharedDtor();
}

void TestMessageIntrusive::SharedDtor() {
  if (this != internal_default_instance()) delete section1_;
  if (this != internal_default_instance()) delete section2_;
}

void TestMessageIntrusive::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TestMessageIntrusive::descriptor() {
  ::protobuf_v3_2fdiff_2fIntrusive_2fTestMessageIntrusive_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_v3_2fdiff_2fIntrusive_2fTestMessageIntrusive_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const TestMessageIntrusive& TestMessageIntrusive::default_instance() {
  ::protobuf_v3_2fdiff_2fIntrusive_2fTestMessageIntrusive_2eproto::InitDefaultsTestMessageIntrusive();
  return *internal_default_instance();
}

TestMessageIntrusive* TestMessageIntrusive::New(::google::protobuf::Arena* arena) const {
  TestMessageIntrusive* n = new TestMessageIntrusive;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void TestMessageIntrusive::Clear() {
// @@protoc_insertion_point(message_clear_start:v3.diff.intrusive.TestMessageIntrusive)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  array_values_.Clear();
  map_values_.Clear();
  if (GetArenaNoVirtual() == NULL && section1_ != NULL) {
    delete section1_;
  }
  section1_ = NULL;
  if (GetArenaNoVirtual() == NULL && section2_ != NULL) {
    delete section2_;
  }
  section2_ = NULL;
  ::memset(&type_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&value6_) -
      reinterpret_cast<char*>(&type_)) + sizeof(value6_));
  _internal_metadata_.Clear();
}

bool TestMessageIntrusive::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:v3.diff.intrusive.TestMessageIntrusive)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .v3.diff.intrusive.MessageType type = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_type(static_cast< ::v3::diff::intrusive::MessageType >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .v3.diff.intrusive.TestMessageIntrusive.TestSection1 section1 = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_section1()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .v3.diff.intrusive.TestMessageIntrusive.TestSection2 section2 = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_section2()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 value5 = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &value5_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double value6 = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(41u /* 41 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &value6_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .v3.diff.intrusive.TestMessageIntrusive.TestSection1 array_values = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(50u /* 50 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(input, add_array_values()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // map<int32, .v3.diff.intrusive.TestMessageIntrusive.TestSection2> map_values = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(58u /* 58 & 0xFF */)) {
          TestMessageIntrusive_MapValuesEntry_DoNotUse::Parser< ::google::protobuf::internal::MapField<
              TestMessageIntrusive_MapValuesEntry_DoNotUse,
              ::google::protobuf::int32, ::v3::diff::intrusive::TestMessageIntrusive_TestSection2,
              ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
              ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
              0 >,
            ::google::protobuf::Map< ::google::protobuf::int32, ::v3::diff::intrusive::TestMessageIntrusive_TestSection2 > > parser(&map_values_);
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
              input, &parser));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:v3.diff.intrusive.TestMessageIntrusive)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:v3.diff.intrusive.TestMessageIntrusive)
  return false;
#undef DO_
}

void TestMessageIntrusive::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:v3.diff.intrusive.TestMessageIntrusive)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .v3.diff.intrusive.MessageType type = 1;
  if (this->type() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->type(), output);
  }

  // .v3.diff.intrusive.TestMessageIntrusive.TestSection1 section1 = 2;
  if (this->has_section1()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, *this->section1_, output);
  }

  // .v3.diff.intrusive.TestMessageIntrusive.TestSection2 section2 = 3;
  if (this->has_section2()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, *this->section2_, output);
  }

  // uint32 value5 = 4;
  if (this->value5() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(4, this->value5(), output);
  }

  // double value6 = 5;
  if (this->value6() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(5, this->value6(), output);
  }

  // repeated .v3.diff.intrusive.TestMessageIntrusive.TestSection1 array_values = 6;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->array_values_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      6, this->array_values(static_cast<int>(i)), output);
  }

  // map<int32, .v3.diff.intrusive.TestMessageIntrusive.TestSection2> map_values = 7;
  if (!this->map_values().empty()) {
    typedef ::google::protobuf::Map< ::google::protobuf::int32, ::v3::diff::intrusive::TestMessageIntrusive_TestSection2 >::const_pointer
        ConstPtr;
    typedef ::google::protobuf::internal::SortItem< ::google::protobuf::int32, ConstPtr > SortItem;
    typedef ::google::protobuf::internal::CompareByFirstField<SortItem> Less;

    if (output->IsSerializationDeterministic() &&
        this->map_values().size() > 1) {
      ::google::protobuf::scoped_array<SortItem> items(
          new SortItem[this->map_values().size()]);
      typedef ::google::protobuf::Map< ::google::protobuf::int32, ::v3::diff::intrusive::TestMessageIntrusive_TestSection2 >::size_type size_type;
      size_type n = 0;
      for (::google::protobuf::Map< ::google::protobuf::int32, ::v3::diff::intrusive::TestMessageIntrusive_TestSection2 >::const_iterator
          it = this->map_values().begin();
          it != this->map_values().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      ::google::protobuf::scoped_ptr<TestMessageIntrusive_MapValuesEntry_DoNotUse> entry;
      for (size_type i = 0; i < n; i++) {
        entry.reset(map_values_.NewEntryWrapper(
            items[static_cast<ptrdiff_t>(i)].second->first, items[static_cast<ptrdiff_t>(i)].second->second));
        ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
            7, *entry, output);
      }
    } else {
      ::google::protobuf::scoped_ptr<TestMessageIntrusive_MapValuesEntry_DoNotUse> entry;
      for (::google::protobuf::Map< ::google::protobuf::int32, ::v3::diff::intrusive::TestMessageIntrusive_TestSection2 >::const_iterator
          it = this->map_values().begin();
          it != this->map_values().end(); ++it) {
        entry.reset(map_values_.NewEntryWrapper(
            it->first, it->second));
        ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
            7, *entry, output);
      }
    }
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:v3.diff.intrusive.TestMessageIntrusive)
}

::google::protobuf::uint8* TestMessageIntrusive::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:v3.diff.intrusive.TestMessageIntrusive)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .v3.diff.intrusive.MessageType type = 1;
  if (this->type() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->type(), target);
  }

  // .v3.diff.intrusive.TestMessageIntrusive.TestSection1 section1 = 2;
  if (this->has_section1()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, *this->section1_, deterministic, target);
  }

  // .v3.diff.intrusive.TestMessageIntrusive.TestSection2 section2 = 3;
  if (this->has_section2()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        3, *this->section2_, deterministic, target);
  }

  // uint32 value5 = 4;
  if (this->value5() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(4, this->value5(), target);
  }

  // double value6 = 5;
  if (this->value6() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(5, this->value6(), target);
  }

  // repeated .v3.diff.intrusive.TestMessageIntrusive.TestSection1 array_values = 6;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->array_values_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        6, this->array_values(static_cast<int>(i)), deterministic, target);
  }

  // map<int32, .v3.diff.intrusive.TestMessageIntrusive.TestSection2> map_values = 7;
  if (!this->map_values().empty()) {
    typedef ::google::protobuf::Map< ::google::protobuf::int32, ::v3::diff::intrusive::TestMessageIntrusive_TestSection2 >::const_pointer
        ConstPtr;
    typedef ::google::protobuf::internal::SortItem< ::google::protobuf::int32, ConstPtr > SortItem;
    typedef ::google::protobuf::internal::CompareByFirstField<SortItem> Less;

    if (deterministic &&
        this->map_values().size() > 1) {
      ::google::protobuf::scoped_array<SortItem> items(
          new SortItem[this->map_values().size()]);
      typedef ::google::protobuf::Map< ::google::protobuf::int32, ::v3::diff::intrusive::TestMessageIntrusive_TestSection2 >::size_type size_type;
      size_type n = 0;
      for (::google::protobuf::Map< ::google::protobuf::int32, ::v3::diff::intrusive::TestMessageIntrusive_TestSection2 >::const_iterator
          it = this->map_values().begin();
          it != this->map_values().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      ::google::protobuf::scoped_ptr<TestMessageIntrusive_MapValuesEntry_DoNotUse> entry;
      for (size_type i = 0; i < n; i++) {
        entry.reset(map_values_.NewEntryWrapper(
            items[static_cast<ptrdiff_t>(i)].second->first, items[static_cast<ptrdiff_t>(i)].second->second));
        target = ::google::protobuf::internal::WireFormatLite::
                   InternalWriteMessageNoVirtualToArray(
                       7, *entry, deterministic, target);
;
      }
    } else {
      ::google::protobuf::scoped_ptr<TestMessageIntrusive_MapValuesEntry_DoNotUse> entry;
      for (::google::protobuf::Map< ::google::protobuf::int32, ::v3::diff::intrusive::TestMessageIntrusive_TestSection2 >::const_iterator
          it = this->map_values().begin();
          it != this->map_values().end(); ++it) {
        entry.reset(map_values_.NewEntryWrapper(
            it->first, it->second));
        target = ::google::protobuf::internal::WireFormatLite::
                   InternalWriteMessageNoVirtualToArray(
                       7, *entry, deterministic, target);
;
      }
    }
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:v3.diff.intrusive.TestMessageIntrusive)
  return target;
}

size_t TestMessageIntrusive::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:v3.diff.intrusive.TestMessageIntrusive)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .v3.diff.intrusive.TestMessageIntrusive.TestSection1 array_values = 6;
  {
    unsigned int count = static_cast<unsigned int>(this->array_values_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->array_values(static_cast<int>(i)));
    }
  }

  // map<int32, .v3.diff.intrusive.TestMessageIntrusive.TestSection2> map_values = 7;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->map_values_size());
  {
    ::google::protobuf::scoped_ptr<TestMessageIntrusive_MapValuesEntry_DoNotUse> entry;
    for (::google::protobuf::Map< ::google::protobuf::int32, ::v3::diff::intrusive::TestMessageIntrusive_TestSection2 >::const_iterator
        it = this->map_values().begin();
        it != this->map_values().end(); ++it) {
      entry.reset(map_values_.NewEntryWrapper(it->first, it->second));
      total_size += ::google::protobuf::internal::WireFormatLite::
          MessageSizeNoVirtual(*entry);
    }
  }

  // .v3.diff.intrusive.TestMessageIntrusive.TestSection1 section1 = 2;
  if (this->has_section1()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *this->section1_);
  }

  // .v3.diff.intrusive.TestMessageIntrusive.TestSection2 section2 = 3;
  if (this->has_section2()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *this->section2_);
  }

  // .v3.diff.intrusive.MessageType type = 1;
  if (this->type() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->type());
  }

  // uint32 value5 = 4;
  if (this->value5() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->value5());
  }

  // double value6 = 5;
  if (this->value6() != 0) {
    total_size += 1 + 8;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void TestMessageIntrusive::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:v3.diff.intrusive.TestMessageIntrusive)
  GOOGLE_DCHECK_NE(&from, this);
  const TestMessageIntrusive* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const TestMessageIntrusive>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:v3.diff.intrusive.TestMessageIntrusive)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:v3.diff.intrusive.TestMessageIntrusive)
    MergeFrom(*source);
  }
}

void TestMessageIntrusive::MergeFrom(const TestMessageIntrusive& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:v3.diff.intrusive.TestMessageIntrusive)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  array_values_.MergeFrom(from.array_values_);
  map_values_.MergeFrom(from.map_values_);
  if (from.has_section1()) {
    mutable_section1()->::v3::diff::intrusive::TestMessageIntrusive_TestSection1::MergeFrom(from.section1());
  }
  if (from.has_section2()) {
    mutable_section2()->::v3::diff::intrusive::TestMessageIntrusive_TestSection2::MergeFrom(from.section2());
  }
  if (from.type() != 0) {
    set_type(from.type());
  }
  if (from.value5() != 0) {
    set_value5(from.value5());
  }
  if (from.value6() != 0) {
    set_value6(from.value6());
  }
}

void TestMessageIntrusive::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:v3.diff.intrusive.TestMessageIntrusive)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TestMessageIntrusive::CopyFrom(const TestMessageIntrusive& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:v3.diff.intrusive.TestMessageIntrusive)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TestMessageIntrusive::IsInitialized() const {
  return true;
}

void TestMessageIntrusive::Swap(TestMessageIntrusive* other) {
  if (other == this) return;
  InternalSwap(other);
}
void TestMessageIntrusive::InternalSwap(TestMessageIntrusive* other) {
  using std::swap;
  array_values_.InternalSwap(&other->array_values_);
  map_values_.Swap(&other->map_values_);
  swap(section1_, other->section1_);
  swap(section2_, other->section2_);
  swap(type_, other->type_);
  swap(value5_, other->value5_);
  swap(value6_, other->value6_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata TestMessageIntrusive::GetMetadata() const {
  protobuf_v3_2fdiff_2fIntrusive_2fTestMessageIntrusive_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_v3_2fdiff_2fIntrusive_2fTestMessageIntrusive_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace intrusive
}  // namespace diff
}  // namespace v3

// @@protoc_insertion_point(global_scope)
