// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v3/diff/UniversalDiff.proto

#ifndef PROTOBUF_v3_2fdiff_2fUniversalDiff_2eproto__INCLUDED
#define PROTOBUF_v3_2fdiff_2fUniversalDiff_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "v3/diff/Transaction.pb.h"
// @@protoc_insertion_point(includes)

namespace protobuf_v3_2fdiff_2fUniversalDiff_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsUniversalDiffImpl();
void InitDefaultsUniversalDiff();
inline void InitDefaults() {
  InitDefaultsUniversalDiff();
}
}  // namespace protobuf_v3_2fdiff_2fUniversalDiff_2eproto
namespace v3 {
namespace diff {
class UniversalDiff;
class UniversalDiffDefaultTypeInternal;
extern UniversalDiffDefaultTypeInternal _UniversalDiff_default_instance_;
}  // namespace diff
}  // namespace v3
namespace v3 {
namespace diff {

// ===================================================================

class UniversalDiff : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:v3.diff.UniversalDiff) */ {
 public:
  UniversalDiff();
  virtual ~UniversalDiff();

  UniversalDiff(const UniversalDiff& from);

  inline UniversalDiff& operator=(const UniversalDiff& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  UniversalDiff(UniversalDiff&& from) noexcept
    : UniversalDiff() {
    *this = ::std::move(from);
  }

  inline UniversalDiff& operator=(UniversalDiff&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const UniversalDiff& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const UniversalDiff* internal_default_instance() {
    return reinterpret_cast<const UniversalDiff*>(
               &_UniversalDiff_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(UniversalDiff* other);
  friend void swap(UniversalDiff& a, UniversalDiff& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline UniversalDiff* New() const PROTOBUF_FINAL { return New(NULL); }

  UniversalDiff* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const UniversalDiff& from);
  void MergeFrom(const UniversalDiff& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(UniversalDiff* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .v3.diff.Transaction transactions = 1;
  int transactions_size() const;
  void clear_transactions();
  static const int kTransactionsFieldNumber = 1;
  const ::v3::diff::Transaction& transactions(int index) const;
  ::v3::diff::Transaction* mutable_transactions(int index);
  ::v3::diff::Transaction* add_transactions();
  ::google::protobuf::RepeatedPtrField< ::v3::diff::Transaction >*
      mutable_transactions();
  const ::google::protobuf::RepeatedPtrField< ::v3::diff::Transaction >&
      transactions() const;

  // @@protoc_insertion_point(class_scope:v3.diff.UniversalDiff)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::v3::diff::Transaction > transactions_;
  mutable int _cached_size_;
  friend struct ::protobuf_v3_2fdiff_2fUniversalDiff_2eproto::TableStruct;
  friend void ::protobuf_v3_2fdiff_2fUniversalDiff_2eproto::InitDefaultsUniversalDiffImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// UniversalDiff

// repeated .v3.diff.Transaction transactions = 1;
inline int UniversalDiff::transactions_size() const {
  return transactions_.size();
}
inline const ::v3::diff::Transaction& UniversalDiff::transactions(int index) const {
  // @@protoc_insertion_point(field_get:v3.diff.UniversalDiff.transactions)
  return transactions_.Get(index);
}
inline ::v3::diff::Transaction* UniversalDiff::mutable_transactions(int index) {
  // @@protoc_insertion_point(field_mutable:v3.diff.UniversalDiff.transactions)
  return transactions_.Mutable(index);
}
inline ::v3::diff::Transaction* UniversalDiff::add_transactions() {
  // @@protoc_insertion_point(field_add:v3.diff.UniversalDiff.transactions)
  return transactions_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::v3::diff::Transaction >*
UniversalDiff::mutable_transactions() {
  // @@protoc_insertion_point(field_mutable_list:v3.diff.UniversalDiff.transactions)
  return &transactions_;
}
inline const ::google::protobuf::RepeatedPtrField< ::v3::diff::Transaction >&
UniversalDiff::transactions() const {
  // @@protoc_insertion_point(field_list:v3.diff.UniversalDiff.transactions)
  return transactions_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace diff
}  // namespace v3

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_v3_2fdiff_2fUniversalDiff_2eproto__INCLUDED
