// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v3/diff/UniversalDiff.proto

#include "v3/diff/UniversalDiff.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace v3 {
namespace diff {
class UniversalDiffDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<UniversalDiff>
      _instance;
} _UniversalDiff_default_instance_;
}  // namespace diff
}  // namespace v3
namespace protobuf_v3_2fdiff_2fUniversalDiff_2eproto {
void InitDefaultsUniversalDiffImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_v3_2fdiff_2fTransaction_2eproto::InitDefaultsTransaction();
  {
    void* ptr = &::v3::diff::_UniversalDiff_default_instance_;
    new (ptr) ::v3::diff::UniversalDiff();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::v3::diff::UniversalDiff::InitAsDefaultInstance();
}

void InitDefaultsUniversalDiff() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsUniversalDiffImpl);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::v3::diff::UniversalDiff, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::v3::diff::UniversalDiff, transactions_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::v3::diff::UniversalDiff)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::v3::diff::_UniversalDiff_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "v3/diff/UniversalDiff.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\033v3/diff/UniversalDiff.proto\022\007v3.diff\032\031"
      "v3/diff/Transaction.proto\";\n\rUniversalDi"
      "ff\022*\n\014transactions\030\001 \003(\0132\024.v3.diff.Trans"
      "actionb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 134);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "v3/diff/UniversalDiff.proto", &protobuf_RegisterTypes);
  ::protobuf_v3_2fdiff_2fTransaction_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_v3_2fdiff_2fUniversalDiff_2eproto
namespace v3 {
namespace diff {

// ===================================================================

void UniversalDiff::InitAsDefaultInstance() {
}
void UniversalDiff::clear_transactions() {
  transactions_.Clear();
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int UniversalDiff::kTransactionsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

UniversalDiff::UniversalDiff()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_v3_2fdiff_2fUniversalDiff_2eproto::InitDefaultsUniversalDiff();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:v3.diff.UniversalDiff)
}
UniversalDiff::UniversalDiff(const UniversalDiff& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      transactions_(from.transactions_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:v3.diff.UniversalDiff)
}

void UniversalDiff::SharedCtor() {
  _cached_size_ = 0;
}

UniversalDiff::~UniversalDiff() {
  // @@protoc_insertion_point(destructor:v3.diff.UniversalDiff)
  SharedDtor();
}

void UniversalDiff::SharedDtor() {
}

void UniversalDiff::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* UniversalDiff::descriptor() {
  ::protobuf_v3_2fdiff_2fUniversalDiff_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_v3_2fdiff_2fUniversalDiff_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const UniversalDiff& UniversalDiff::default_instance() {
  ::protobuf_v3_2fdiff_2fUniversalDiff_2eproto::InitDefaultsUniversalDiff();
  return *internal_default_instance();
}

UniversalDiff* UniversalDiff::New(::google::protobuf::Arena* arena) const {
  UniversalDiff* n = new UniversalDiff;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void UniversalDiff::Clear() {
// @@protoc_insertion_point(message_clear_start:v3.diff.UniversalDiff)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  transactions_.Clear();
  _internal_metadata_.Clear();
}

bool UniversalDiff::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:v3.diff.UniversalDiff)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .v3.diff.Transaction transactions = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(input, add_transactions()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:v3.diff.UniversalDiff)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:v3.diff.UniversalDiff)
  return false;
#undef DO_
}

void UniversalDiff::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:v3.diff.UniversalDiff)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .v3.diff.Transaction transactions = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->transactions_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->transactions(static_cast<int>(i)), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:v3.diff.UniversalDiff)
}

::google::protobuf::uint8* UniversalDiff::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:v3.diff.UniversalDiff)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .v3.diff.Transaction transactions = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->transactions_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->transactions(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:v3.diff.UniversalDiff)
  return target;
}

size_t UniversalDiff::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:v3.diff.UniversalDiff)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .v3.diff.Transaction transactions = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->transactions_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->transactions(static_cast<int>(i)));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void UniversalDiff::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:v3.diff.UniversalDiff)
  GOOGLE_DCHECK_NE(&from, this);
  const UniversalDiff* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const UniversalDiff>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:v3.diff.UniversalDiff)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:v3.diff.UniversalDiff)
    MergeFrom(*source);
  }
}

void UniversalDiff::MergeFrom(const UniversalDiff& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:v3.diff.UniversalDiff)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  transactions_.MergeFrom(from.transactions_);
}

void UniversalDiff::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:v3.diff.UniversalDiff)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void UniversalDiff::CopyFrom(const UniversalDiff& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:v3.diff.UniversalDiff)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UniversalDiff::IsInitialized() const {
  return true;
}

void UniversalDiff::Swap(UniversalDiff* other) {
  if (other == this) return;
  InternalSwap(other);
}
void UniversalDiff::InternalSwap(UniversalDiff* other) {
  using std::swap;
  transactions_.InternalSwap(&other->transactions_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata UniversalDiff::GetMetadata() const {
  protobuf_v3_2fdiff_2fUniversalDiff_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_v3_2fdiff_2fUniversalDiff_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace diff
}  // namespace v3

// @@protoc_insertion_point(global_scope)
