# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: status2.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='status2.proto',
  package='v2',
  syntax='proto2',
  serialized_pb=_b('\n\rstatus2.proto\x12\x02v2\"\'\n\x07Status2\x12\x0e\n\x06status\x18\x01 \x02(\x05\x12\x0c\n\x04lang\x18\x02 \x01(\t')
)




_STATUS2 = _descriptor.Descriptor(
  name='Status2',
  full_name='v2.Status2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='v2.Status2.status', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lang', full_name='v2.Status2.lang', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=60,
)

DESCRIPTOR.message_types_by_name['Status2'] = _STATUS2
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Status2 = _reflection.GeneratedProtocolMessageType('Status2', (_message.Message,), dict(
  DESCRIPTOR = _STATUS2,
  __module__ = 'status2_pb2'
  # @@protoc_insertion_point(class_scope:v2.Status2)
  ))
_sym_db.RegisterMessage(Status2)


# @@protoc_insertion_point(module_scope)
