# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v3/diff/UniversalDiff.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from v3.diff import Transaction_pb2 as v3_dot_diff_dot_Transaction__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='v3/diff/UniversalDiff.proto',
  package='v3.diff',
  syntax='proto3',
  serialized_pb=_b('\n\x1bv3/diff/UniversalDiff.proto\x12\x07v3.diff\x1a\x19v3/diff/Transaction.proto\";\n\rUniversalDiff\x12*\n\x0ctransactions\x18\x01 \x03(\x0b\x32\x14.v3.diff.Transactionb\x06proto3')
  ,
  dependencies=[v3_dot_diff_dot_Transaction__pb2.DESCRIPTOR,])




_UNIVERSALDIFF = _descriptor.Descriptor(
  name='UniversalDiff',
  full_name='v3.diff.UniversalDiff',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='transactions', full_name='v3.diff.UniversalDiff.transactions', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=126,
)

_UNIVERSALDIFF.fields_by_name['transactions'].message_type = v3_dot_diff_dot_Transaction__pb2._TRANSACTION
DESCRIPTOR.message_types_by_name['UniversalDiff'] = _UNIVERSALDIFF
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UniversalDiff = _reflection.GeneratedProtocolMessageType('UniversalDiff', (_message.Message,), dict(
  DESCRIPTOR = _UNIVERSALDIFF,
  __module__ = 'v3.diff.UniversalDiff_pb2'
  # @@protoc_insertion_point(class_scope:v3.diff.UniversalDiff)
  ))
_sym_db.RegisterMessage(UniversalDiff)


# @@protoc_insertion_point(module_scope)
