SET(PROTO_SOURCES
    ${CMAKE_CURRENT_SOURCE_DIR}/v2/Status2.pb.h
    ${CMAKE_CURRENT_SOURCE_DIR}/v2/Status2.pb.cc
    ${CMAKE_CURRENT_SOURCE_DIR}/v3/AllFieldsMessage.pb.h
    ${CMAKE_CURRENT_SOURCE_DIR}/v3/AllFieldsMessage.pb.cc
    ${CMAKE_CURRENT_SOURCE_DIR}/v3/Status3.pb.h
    ${CMAKE_CURRENT_SOURCE_DIR}/v3/Status3.pb.cc
    ${CMAKE_CURRENT_SOURCE_DIR}/v3/Trash.pb.h
    ${CMAKE_CURRENT_SOURCE_DIR}/v3/Trash.pb.cc
    ${CMAKE_CURRENT_SOURCE_DIR}/v3/big_bin/BigBinV1.pb.h
    ${CMAKE_CURRENT_SOURCE_DIR}/v3/big_bin/BigBinV1.pb.cc
    ${CMAKE_CURRENT_SOURCE_DIR}/v3/big_bin/BigBinV2.pb.h
    ${CMAKE_CURRENT_SOURCE_DIR}/v3/big_bin/BigBinV2.pb.cc
    ${CMAKE_CURRENT_SOURCE_DIR}/v3/big_bin/BigBinV3.pb.h
    ${CMAKE_CURRENT_SOURCE_DIR}/v3/big_bin/BigBinV3.pb.cc
    ${CMAKE_CURRENT_SOURCE_DIR}/v3/big_message/BigMessage.pb.h
    ${CMAKE_CURRENT_SOURCE_DIR}/v3/big_message/BigMessage.pb.cc
    ${CMAKE_CURRENT_SOURCE_DIR}/v3/diff/Intrusive/IntrusiveDiff.pb.h
    ${CMAKE_CURRENT_SOURCE_DIR}/v3/diff/Intrusive/IntrusiveDiff.pb.cc
    ${CMAKE_CURRENT_SOURCE_DIR}/v3/diff/Intrusive/TestMessageIntrusive.pb.h
    ${CMAKE_CURRENT_SOURCE_DIR}/v3/diff/Intrusive/TestMessageIntrusive.pb.cc
    ${CMAKE_CURRENT_SOURCE_DIR}/v3/diff/Universal/TestMessage.pb.h
    ${CMAKE_CURRENT_SOURCE_DIR}/v3/diff/Universal/TestMessage.pb.cc
    ${CMAKE_CURRENT_SOURCE_DIR}/v3/diff/Universal/Transaction.pb.h
    ${CMAKE_CURRENT_SOURCE_DIR}/v3/diff/Universal/Transaction.pb.cc
    ${CMAKE_CURRENT_SOURCE_DIR}/v3/diff/Universal/UniversalDiff.pb.h
    ${CMAKE_CURRENT_SOURCE_DIR}/v3/diff/Universal/UniversalDiff.pb.cc)