SET(PROTO_SOURCES
    ${CMAKE_CURRENT_SOURCE_DIR}/v2/Status2.pb.h
    ${CMAKE_CURRENT_SOURCE_DIR}/v2/Status2.pb.cc
    ${CMAKE_CURRENT_SOURCE_DIR}/v3/AllFieldsMessage.pb.h
    ${CMAKE_CURRENT_SOURCE_DIR}/v3/AllFieldsMessage.pb.cc
    ${CMAKE_CURRENT_SOURCE_DIR}/v3/Status3.pb.h
    ${CMAKE_CURRENT_SOURCE_DIR}/v3/Status3.pb.cc
    ${CMAKE_CURRENT_SOURCE_DIR}/v3/big_bin/BigBinV1.pb.h
    ${CMAKE_CURRENT_SOURCE_DIR}/v3/big_bin/BigBinV1.pb.cc
    ${CMAKE_CURRENT_SOURCE_DIR}/v3/big_bin/BigBinV2.pb.h
    ${CMAKE_CURRENT_SOURCE_DIR}/v3/big_bin/BigBinV2.pb.cc
    ${CMAKE_CURRENT_SOURCE_DIR}/v3/big_bin/BigBinV3.pb.h
    ${CMAKE_CURRENT_SOURCE_DIR}/v3/big_bin/BigBinV3.pb.cc
    ${CMAKE_CURRENT_SOURCE_DIR}/v3/big_message/BigMessage.pb.h
    ${CMAKE_CURRENT_SOURCE_DIR}/v3/big_message/BigMessage.pb.cc)